4 responsive breakpoints
ccsCoder/ng-weather pull request #7
Opened 2020-10-18 11:50 UTC by ravenblack24

# Introduction
We'd like to add responsive breakpoints so the application can be viewed in as many devices and browsers as possible.

# This PR
In this PR I've added breakpoints where necessary for the following breakpoints
- Mobile (default styling)
- Mobile landscape @ 320px - 767px landscape
- Tablet @ 768px
- Tablet landscape & desktop @ 992px

# Screenshots
![mobile-portrait](https://user-images.githubusercontent.com/19981420/96366594-641af700-1140-11eb-94e7-a27613fd2f67.PNG)
![mobile-portrait2](https://user-images.githubusercontent.com/19981420/96366597-69784180-1140-11eb-9e1c-dbc018010b39.PNG)
![mobile-landscape2](https://user-images.githubusercontent.com/19981420/96366598-6b420500-1140-11eb-9aec-ccfa0f009a1d.PNG)
![tablet-portrait](https://user-images.githubusercontent.com/19981420/96366601-6e3cf580-1140-11eb-8966-abf8d5101fcc.PNG)
![tablet-landscape](https://user-images.githubusercontent.com/19981420/96366604-6f6e2280-1140-11eb-9b62-4a1575632505.PNG)

2020-10-20 04:09 UTC, ccsCoder commented
This looks good. I think a small change in Tablet Landscape mode is needed.
Let's make the City Name font larger, while reducing the size of the left part ( temperature and cloud icons )
With that done, I can merge your PR.

2020-10-20 04:10 UTC, ccsCoder requested changes
For Tablet Landscape mode, let us make the City name larger while decreasing the size of the left portion ( temperature and cloud icons ).
Apart from that, everything else looks good to me.

2020-10-20 09:24 UTC, ravenblack24 commented
Code updated and after adjustments tablet landscape now looks like:
![tablet-landscape-new](https://user-images.githubusercontent.com/19981420/96567148-5f7c4d00-12be-11eb-85ea-cad9fcf28113.PNG)

2020-10-22 12:17 UTC, ccsCoder approved these changes
Looks good to me.
Thank you for your contribution.

2020-10-22 12:17 UTC, merged